import {StyleSheet, Text, View, Image, TouchableOpacity} from 'react-native';
import React from 'react';
import {scaleSize} from 'utils/index';
import Colors from 'constants/Colors';
import {Family, FontSize, FontSizeModerate} from 'constants/Fonts';

// Importing images
import billImage from '../../../images/subscribers/bill.png';
import threeDots from '../../../images/subscribers/three_dots.png';
import online from '../../../images/subscribers/online.png';
import dateIcon from '../../../images/subscribers/date.png';
import TimeIcon from '../../../images/subscribers/time.png';
import {useNavigation} from '@react-navigation/native';

const RechargeBillCard = () => {
  const navigation = useNavigation();
  console.log('NAVIGATION FROM SUBSCRIBERS SCREEN', navigation);
  return (
    <View style={styles.wrapper}>
      <View style={styles.innerWrapperTop}>
        <View style={styles.billTitleWrapper}>
          <View style={styles.detailsWrapper}>
            <View style={styles.profileImageWrapper}>
              <Image style={styles.profileImage} source={billImage} />
            </View>
            <View style={styles.userDetailWrapper}>
              <View style={styles.userNameWrapper}>
                <Text style={styles.userText}>{'\u20B9'} 100</Text>
              </View>
              <Text style={styles.userSubText}>KL00000986867556</Text>
            </View>
          </View>
          <View style={styles.actionWrapper}>
            <TouchableOpacity style={styles.activeWrapper}>
              <Text style={styles.activeText}>Resolve</Text>
            </TouchableOpacity>
          </View>
        </View>
        <View style={styles.billInfoWrapper}>
          <View style={styles.billInfo}>
            <View style={styles.rowText}>
              <Text style={styles.billLabel}>Coupon Name </Text>
              <Text style={styles.billText}>Coupon01</Text>
            </View>
            <View style={styles.rowText}>
              <Text style={styles.billLabel}>Coupon Value </Text>
              <Text style={styles.billText}>012</Text>
            </View>
          </View>
          <View style={styles.billInfo}>
            <View style={styles.rowText}>
              <Text style={styles.billLabel}>Generated by</Text>
              <Text style={styles.billText}>Admin</Text>
            </View>
          </View>
        </View>
      </View>
      {/* Card bottom section */}
      <View style={styles.innerWrapperBottom}>
        <View style={styles.expirydateWrapper}>
          <Image source={dateIcon} style={styles.date} />
          <Text style={styles.expiryDate}>11-10-2022</Text>
        </View>
        <View style={styles.expirydateWrapper}>
          <Image source={TimeIcon} style={styles.date} />
          <Text style={styles.expiryDate}>9:56</Text>
        </View>
        <View style={styles.expirydateWrapper}>
          <Image source={dateIcon} style={styles.date} />
          <Text style={styles.expiryDateLabel}>Expiry Date</Text>
          <Text style={styles.expiryDate}>11-10-2022</Text>
        </View>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  wrapper: {
    backgroundColor: '#F4F6F9',
    marginBottom: 10,
    borderRadius: scaleSize(10),
  },
  billTitleWrapper: {
    flexDirection: 'row',
    backgroundColor: '#F4F6F9',
    borderRadius: scaleSize(10),
    paddingTop: scaleSize(16),
    paddingBottom: scaleSize(14),
    paddingHorizontal: scaleSize(16),
    marginBottom: 10,
  },
  detailsWrapper: {
    flexDirection: 'row',
    flex: 3,
  },
  profileImageWrapper: {
    marginRight: scaleSize(15),
  },
  profileImage: {height: scaleSize(50), width: scaleSize(50)},
  userDetailWrapper: {
    justifyContent: 'center',
  },
  userNameWrapper: {
    flexDirection: 'row',
    marginBottom: scaleSize(5),
    alignItems: 'center',
  },
  userText: {
    fontFamily: Family.bold,
    fontSize: FontSizeModerate.regular,
    color: Colors.userText,
    marginRight: scaleSize(3),
  },
  userSubText: {
    color: Colors.userSubText,
    fontFamily: Family.semibold,
    fontSize: FontSize.xs,
  },

  actionWrapper: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
  },

  activeWrapper: {
    paddingHorizontal: scaleSize(9),
    paddingVertical: scaleSize(3),
    // marginTop: scaleSize(14),
    backgroundColor: '#31B447',
    borderRadius: 14,
  },
  activeText: {
    fontFamily: Family.semibold,
    fontSize: FontSize.small,
    color: Colors.white,
  },
  billInfoWrapper: {
    flexDirection: 'row',
    paddingHorizontal: scaleSize(16),
    // backgroundColor: 'red',
  },
  billInfo: {
    flex: 1,
  },
  rowText: {
    flexDirection: 'row',
  },
  billLabel: {
    fontFamily: Family.regular,
    fontSize: FontSizeModerate.small,
    color: Colors.userText,
    marginBottom: scaleSize(6),
  },
  billText: {
    fontFamily: Family.semibold,
    fontSize: FontSizeModerate.small,
    color: Colors.userText,
  },

  expirydateWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: scaleSize(4),
  },
  expiryDateLabel: {
    fontFamily: Family.regular,
    fontSize: FontSize.small,
    color: Colors.userText,
    paddingRight: scaleSize(2),
  },
  expiryDate: {
    fontFamily: Family.semibold,
    fontSize: FontSizeModerate.small,
    color: Colors.userText,
  },
  date: {
    height: scaleSize(14),
    width: scaleSize(14),
    marginRight: scaleSize(4),
  },
  innerWrapperBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: scaleSize(14),
    paddingHorizontal: scaleSize(12),
    borderTopWidth: 1,
    borderTopColor: '#DCDCDC',
    borderStyle: 'dashed',
    // backgroundColor: 'red',
  },
});

export default RechargeBillCard;
